require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1

Bundler/DuplicatedGem:
  Enabled: true

Layout/ParameterAlignment:
  Enabled: true

Layout/ClosingParenthesisIndentation:
  Enabled: true

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  Enabled: true

Layout/MultilineArrayBraceLayout:
  Enabled: true

Layout/MultilineBlockLayout:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true

Layout/MultilineMethodCallBraceLayout:
  Enabled: true

Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: true

Layout/MultilineOperationIndentation:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Lint/AmbiguousBlockAssociation:
  Enabled: true

Lint/AmbiguousRegexpLiteral:
  Enabled: true

Lint/SuppressedException:
  Enabled: true

Lint/ScriptPermission:
  Enabled: true

Lint/UnifiedInteger:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Lint/UriEscapeUnescape:
  Enabled: true

Metrics/AbcSize:
  Enabled: true

Metrics/ClassLength:
  Enabled: true

Metrics/CyclomaticComplexity:
  Max: 12

Layout/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 60

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: true

Metrics/PerceivedComplexity:
  Enabled: true

Naming/FileName:
  Enabled: true

Naming/HeredocDelimiterNaming:
  Enabled: true

Naming/PredicateName:
  Enabled: true

Naming/VariableNumber:
  Enabled: true

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/BlockDelimiters:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: true

Style/Documentation:
  AllowedConstants: ['Test']

Style/DoubleNegation:
  Enabled: true

Style/EachWithObject:
  Enabled: true

Style/Encoding:
  Enabled: true

Style/FormatString:
  EnforcedStyle: sprintf

Style/FrozenStringLiteralComment:
  Enabled: true

Style/GuardClause:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: true

Style/Lambda:
  Enabled: true

Style/MultilineBlockChain:
  Enabled: true

Style/NegatedIf:
  Enabled: true

Style/Next:
  Enabled: true

Style/NumericLiteralPrefix:
  Enabled: true

Style/NumericLiterals:
  Enabled: true

Style/NumericPredicate:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: true

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RedundantSelf:
  Enabled: true

Style/RescueModifier:
  Enabled: true

Style/SafeNavigation:
  Enabled: true

Style/SignalException:
  Enabled: true

Style/SingleLineBlockParams:
  Enabled: true

Style/StructInheritance:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/TernaryParentheses:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true

Style/TrailingUnderscoreVariable:
  Enabled: true

Style/TrivialAccessors:
  Enabled: true

Style/WordArray:
  Enabled: true

Style/ZeroLengthPredicate:
  Enabled: true

Metrics/BlockLength:
  Enabled: true

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Gemspec/DevelopmentDependencies:
  Enabled: true

Gemspec/RequireMFA:
  Enabled: true

Layout/LineContinuationLeadingSpace:
  Enabled: true

Layout/LineContinuationSpacing:
  Enabled: true

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

Lint/AmbiguousOperatorPrecedence:
  Enabled: true

Lint/AmbiguousRange:
  Enabled: true

Lint/ConstantOverwrittenInRescue:
  Enabled: true

Lint/DeprecatedConstants:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateMagicComment:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/EmptyInPattern:
  Enabled: true

Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/NonAtomicFileOperation:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/RefinementImportMethods:
  Enabled: true

Lint/RequireRangeParentheses:
  Enabled: true

Lint/RequireRelativeSelfPath:
  Enabled: true

Lint/SymbolConversion:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/TripleQuotes:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/UselessRescue:
  Enabled: true

Lint/UselessRuby2Keywords:
  Enabled: true

Metrics/CollectionLiteralLength:
  Enabled: true

Naming/BlockForwarding:
  Enabled: true

Security/CompoundHash:
  Enabled: true

Security/IoMethods:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true

Style/ArrayIntersect:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/ComparableClamp:
  Enabled: true

Style/ConcatArrayLiterals:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/EmptyHeredoc:
  Enabled: true

Style/EndlessMethod:
  Enabled: true

Style/EnvHome:
  Enabled: true

Style/FetchEnvVar:
  Enabled: true

Style/FileRead:
  Enabled: true

Style/FileWrite:
  Enabled: true

Style/HashConversion:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/InPatternThen:
  Enabled: true

Style/MagicCommentFormat:
  Enabled: true

Style/MapCompactWithConditionalBlock:
  Enabled: true

Style/MapToHash:
  Enabled: true

Style/MapToSet:
  Enabled: true

Style/MinMaxComparison:
  Enabled: true

Style/MultilineInPatternThen:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/NestedFileDirname:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/NumberedParameters:
  Enabled: true

Style/NumberedParametersLimit:
  Enabled: true

Style/ObjectThen:
  Enabled: true

Style/OpenStructUse:
  Enabled: true

Style/OperatorMethodCall:
  Enabled: true

Style/QuotedSymbols:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Style/RedundantConstantBase:
  Enabled: true

Style/RedundantDoubleSplatHashBraces:
  Enabled: true

Style/RedundantEach:
  Enabled: true

Style/RedundantHeredocDelimiterQuotes:
  Enabled: true

Style/RedundantInitialize:
  Enabled: true

Style/RedundantSelfAssignmentBranch:
  Enabled: true

Style/RedundantStringEscape:
  Enabled: true

Style/SelectByRegexp:
  Enabled: true

Style/StringChars:
  Enabled: true

Style/SwapValues:
  Enabled: true

Capybara/MatchStyle:
  Enabled: true

Capybara/NegationMatcher:
  Enabled: true

Capybara/SpecificActions:
  Enabled: true

Capybara/SpecificFinders:
  Enabled: true

Capybara/SpecificMatcher:
  Enabled: true

RSpec/BeEq:
  Enabled: true

RSpec/BeNil:
  Enabled: true

RSpec/ChangeByZero:
  Enabled: true

RSpec/DuplicatedMetadata:
  Enabled: true

RSpec/ExcessiveDocstringSpacing:
  Enabled: true

RSpec/IdenticalEqualityAssertion:
  Enabled: true

RSpec/NoExpectationExample:
  Enabled: true

RSpec/PendingWithoutReason:
  Enabled: true

RSpec/SortMetadata:
  Enabled: true

RSpec/SubjectDeclaration:
  Enabled: true

RSpec/VerifiedDoubleReference:
  Enabled: true

RSpec/FactoryBot/ConsistentParenthesesStyle:
  Enabled: true

RSpec/FactoryBot/FactoryNameStyle:
  Enabled: true

RSpec/FactoryBot/SyntaxMethods:
  Enabled: true

RSpec/Rails/AvoidSetupHook:
  Enabled: true

RSpec/Rails/HaveHttpStatus:
  Enabled: true

RSpec/Rails/InferredSpecType:
  Enabled: true

RSpec/Rails/MinitestAssertions:
  Enabled: true

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
